Fix ctrl+[ not getting out of insert mode
MovingtoMars/liner pull request #88
Opened 2018-05-29 19:12 UTC by liamnaddell

This issue should be resolved with the following patch

2018-05-29 19:48 UTC, iamcodemaker requested changes

2018-05-29 19:48 UTC, iamcodemaker commented on src/keymap/vi.rs
> +            try!(self.handle_key_core(Key::Ctrl('[')));
This should be removed.

2018-05-29 19:48 UTC, iamcodemaker commented on src/keymap/vi.rs
> +    fn vi_switch_from_insert_ctrl_lb() {
Instead of duplicating this test with `ctrl-[`, replace some (or all) of the `Esc` presses in the original test with `ctrl-[`.

2018-05-29 22:22 UTC, liamnaddell commented
I added a new commit bb84002 that should address your concerns

2018-05-29 23:05 UTC, iamcodemaker approved these changes

2018-06-03 00:53 UTC, liamnaddell commented
Oops didn't mean to add the commit "Add upstream fork commits except 1" to this pr!" Sorry

2018-06-03 16:21 UTC, closed without merging